ktamr:
  webVersion: V2.6.5
  version: 2.6.5
  dbVersion: V2.8.0
  profile: "E:\\ktamr\\YM\\"

#服务配置
server:
  #访问端口号80
  port: 8888
  servlet:
    #配置项目的访问路径(默认是:/)
    context-path: /
  tomcat:
    #配置tomcat字符编码是UTF-8
    uri-encoding: UTF-8
    #配置tomcat最大线程数是800
    max-threads: 800
    #配置tomcat初始化线程是30
    min-spare-threads: 30

#配置spring
spring:
  profiles:
    #配置druid路径
    #active: druid
    #配置8884另一个数据库
    active: other
    #配置thymeleaf前端模板
  thymeleaf:
    cache: false
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  #redis:
    #host: 106.14.72.179
    #password: redispassword
    #port: 6379
    #pool:
      #max-idle: 100
      #min-idle: 1
      #max-active: 1000
      #max-wait: -1
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
      resolve-lazily: false

#配置mybatis
mybatis:
  #设置路径
  typeAliasesPackage: com.ktamr
  #配置mapper.xml,扫描映射所有匹配到的Mapper.xml
  mapperLocations: [classpath*:mapper/**/*Mapper.xml,classpath*:mapper/**/**/*Mapper.xml]
  #配置mybatis-config.xml全局文件
  configLocation: classpath:mapper/mybatis-config.xml

# 日志配置
logging:
  level:
    com.ktamr: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug


# Shiro
shiro:
  operator:
    # 登录地址
    loginUrl: /login
    # 首页地址
    indexUrl: /index
  session:
    #session超时时间默认30分钟
    expireTime: 30

